# Generated by Django 5.0.7 on 2024-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('cart_id', models.IntegerField()),
            ],
        ),
    ]
