# Generated by Django 5.0.7 on 2024-07-16 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('employee_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.TextField()),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('categories', models.TextField()),
                ('brand_name', models.CharField(max_length=255)),
                ('Images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('swller_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('alter_mobile', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=10)),
                ('amout', models.IntegerField()),
                ('transaction_status', models.CharField(max_length=10)),
                ('ip_address', models.IntegerField()),
                ('response_code', models.IntegerField()),
                ('response_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cart_id',
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
            ],
        ),
    ]
